services:
  main:
    build: .
    entrypoint: [ "python", "main.py" ]
    volumes:
      - ./result:/result
      - ./config:/config
      - ./dataclass:/dataclass

  test1:
    build: .
    entrypoint: [ "python", "main.py", "1aCats.json" ]
    volumes:
      - ./result:/result
      - ./config:/config
      - ./dataclass:/dataclass
  test2:
    build: .
    entrypoint: [ "python", "main.py", "1bFullTest.json" ]
    volumes:
      - ./result:/result
      - ./config:/config
      - ./dataclass:/dataclass
  test3:
    build: .
    entrypoint: [ "python", "main.py", "2aBank.json" ]
    volumes:
      - ./result:/result
      - ./config:/config
      - ./dataclass:/dataclass
  test4:
    build: .
    entrypoint: [ "python", "main.py", "2bAnime.json" ]
    volumes:
      - ./result:/result
      - ./config:/config
      - ./dataclass:/dataclass
